name: 'Import Scanner Results to ScanDog'
description: 'A GitHub Action to import scanner results into the ScanDog platform.'
author: 'ScanDog Team'
inputs:
  report_file:
    description: 'Path to the scanner results file (JSON format).'
    required: true
  workflow_id:
    description: 'The identifier for the workflow.'
    required: true
  scan_type:
    description: 'The type of scan (e.g., FullScan, QuickScan).'
    required: true
  scanner:
    description: 'The name of the scanner (e.g., AWS Inspector, Snyk).'
    required: true
  backend_api_token:
    description: 'The API token for authenticating with ScanDog.'
    required: true
    secret: true
  backend_url:
    description: 'The base URL of the ScanDog API.'
    required: true
outputs:
  status:
    description: 'Status of the import operation (success/failure).'
  response:
    description: 'Full response text from the ScanDog API.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CI_RUN_ID: ${{ github.run_id }}
    REPORT_FILE: ${{ inputs.report_file }}
    WORKFLOW_ID: ${{ inputs.workflow_id }}
    SCAN_TYPE: ${{ inputs.scan_type }}
    SCANNER: ${{ inputs.scanner }}
    BACKEND_API_TOKEN: ${{ inputs.backend_api_token }}
    BACKEND_URL: ${{ inputs.backend_url }}

branding:
  icon: 'upload-cloud'
  color: 'blue'